{{- range $tool := .Values.helmTools}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-tool-{{$tool.name}}
  namespace: argocd
  labels:
    component: tooling
    type: helm
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: {{$tool.repoURL}}
      chart: {{$tool.chart}}
      targetRevision: {{$tool.targetRevision}}
      helm:
        releaseName: {{$tool.releaseName}}
        valueFiles:
          - $values/00-tooling/{{$tool.name}}/{{$tool.valuesFile}}
    - repoURL: {{$.Values.repoURL}}
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{$tool.namespace}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end}}

{{- range $cr := .Values.crTools }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-tool-{{ $cr.name }}-crs
  namespace: argocd
  labels:
    component: tooling
    type: cr
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: HEAD
    path: {{ $cr.path }}
    kustomize: { }
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $cr.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
{{- end }}