apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-tooling
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{.Values.repoURL}}
    targetRevision: HEAD
    path: 00-tooling
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true