apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
namespace: dev

patches:
  - target:
        kind: Deployment
        name: bank-core
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
          name: bank-core
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: bank-core
                resources:
                  requests:
                    cpu: 100m
                    memory: 128Mi
      #  Hardcoding the credentials for the sake of developing speed. I will create a dedicated secret manager later.
                env:
                  - name: SPRING_PROFILES_ACTIVE
                    value: dev
                  - name: SPRING_DATASOURCE_URL
                    value: jdbc:postgresql://ledger-db-primary.postgres.svc:5432/ledger-db
                  - name: SPRING_DATASOURCE_USERNAME
                    value: ledger
                  - name: SPRING_DATASOURCE_PASSWORD
                    value: OvY;T48/U1e>MU2|8Qp[l)7(
