apiVersion: Postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: users-db
  namespace: postgres
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.4-0
  postgresVersion: 15
  instances:
    - name: primary
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      volumeClaimSpec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.45-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessMode: [ReadWriteOnce]
              resources:
                requests:
                  storage: 1Gi
  users:
    - name: identity
      database: [userdb]
      options: "SUPERUSER"